# Generated by Django 5.0 on 2023-12-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0004_contacts_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='surname',
        ),
    ]
